---
swagger: "2.0"
info:
  version: "2020-05-20T10:39:47Z"
  title: "apiproxyfunction"

basePath: "/test"
schemes:
- "https"
paths:
  /submit:
    post:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
                 uri: "arn:aws:apigateway:us-east-2:lambda:path/2020-05-20/functions/{{ arn:aws:lambda:us-east-2:411814071376:function:insertdatetime}}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
